# example values
server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

  datasource:
    username: root
    password: ${MYSQL_ROOT_PASSWORD:1gjAVnJ}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE:search_engine}?rewriteBatchedStatements=true
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers_skip_column_definitions: true
        globally_quoted_identifiers: true
        order_inserts: true
        jdbc:
          batch_size: 200
    generate-ddl: true

  sql:
    init:
      mode: always
      platform: mysql

indexing-settings:
  sites:
    - url: https://www.svetlovka.ru
      name: Svetlovka
    - url: https://www.playback.ru
      name: PlayBack