# example values
server:
  port: 8080
spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  datasource:
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/search_engine
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers_skip_column_definitions: true
        globally_quoted_identifiers: true
        order_inserts: true
        jdbc:
          batch_size: 100
    generate-ddl: true
  sql:
    init:
      mode: always
      platform: mysql
indexing-settings:
  sites:
    - url: https://sendel.ru
      name: Sendel.Ru