# example values
server:
  port: 8080
spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cupuyc
    password: "password"
    url: jdbc:mysql://spare.lan:3306/search_engine
    name: search_engine
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        globally_quoted_identifiers_skip_column_definitions: true
        globally_quoted_identifiers: true
    generate-ddl: true
  sql:
    init:
      mode: always
      platform: mysql
indexing-settings:
  userAgent: "Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6"
  referrer: "http://www.google.com"
  sites:
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://volochek.life
      name: VOLOCHEK.LIFE